### ISSUE TITLE
kerberos support issue

### ISSUE THREAD

**Issue by damonlinn** [beltran/gosasl#14]
msg:
panic: gosasl was installed without kerberos support please reinstall with `go get` using the flags `build kerberos`

I have run command on mac to install kerberos support, but still not working. could you help to fix the issue?

command: 
go get -u -tags kerberos github.com/beltran/gosasl
output:
$ go get -u -tags kerberos github.com/beltran/gosasl
go: finding github.com/beltran/gosasl latest
go: finding github.com/beltran/gssapi latest

command:
output:
$ ll /Users/xx/go/pkg/mod/github.com/beltran
total 0
dr-x------  16 xx  staff  512  3 23 16:22 gohive@v1.0.1
dr-x------  27 xx  staff  864  3 23 16:22 gssapi@v0.0.0-20180807003338-598f9f3b2878
dr-x------  13 xx  staff  416  3 23 16:26 gosasl@v0.0.0-20181023043315-01c4c2ce6a51
dr-x------  13 xx  staff  416  3 23 16:31 gosasl@v0.0.0-20200309143703-479940a0a460

**Comment by beltran** [comment]
Some things you can try:
* [Completely remove](https://stackoverflow.com/a/13792319/2176566) gosasl and install again with `go get -tags kerberos github.com/beltran/gosasl`
* Make sure kerberos is properly installed in mac (you can run kinit, klist)

**Comment by damonlinn** [comment]
thanks, I complete remove the package and try again reinstall kerberos suppport, but still encounter issue like below,.

xxdeMacBook-Pro:go xx$ go get -tags kerberos github.com/beltran/gosasl
go: finding github.com/beltran/gosasl latest
go: extracting github.com/beltran/gosasl v0.0.0-20200309143703-479940a0a460
#github.com/beltran/gssapi
pkg/mod/github.com/beltran/gssapi@v0.0.0-20180807003338-598f9f3b2878/name.go:26:39: error: typedef redefinition with different types ('const struct gss_name_struct *' vs 'const struct gss_name_t_desc_struct *')
typedef const struct gss_name_struct *gss_const_name_t;
                                      ^
/usr/local/opt/heimdal/include/gssapi/gssapi.h:94:46: note: previous definition is here
typedef const struct gss_name_t_desc_struct *gss_const_name_t;
                                             ^
1 error generated.

in addition , kerberos is installed in mac, kinit,klist work fine.

heimdal version information.

xxdeMacBook-Pro:~ xx$ brew info heimdal
heimdal: stable 7.6.0 (bottled) [keg-only]
Free Kerberos 5 implementation
https://www.h5l.org
/usr/local/Cellar/heimdal/7.6.0_1 (1,880 files, 19.5MB)
  Poured from bottle on 2020-03-23 at 09:50:56
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/heimdal.rb

**Comment by beltran** [comment]
I see, this looks like a genuine bug in mac, I can't repro but I think the latest commit fixes this. Can you completely remove gosasl and try again?

**Comment by damonlinn** [comment]
thanks, I remove the gosasl and try agian, it works now. and I found gohive kerberos support also have this issue in my mac ,can you help to fix it ?

* install gosasl success.
xxdeMacBook-Pro:go xx$ go get github.com/beltran/gosasl
go: finding github.com/beltran/gosasl latest
go: downloading github.com/beltran/gosasl v0.0.0-20200324154900-112336fc0fc0
go: extracting github.com/beltran/gosasl v0.0.0-20200324154900-112336fc0fc0
go: downloading github.com/beltran/gssapi v0.0.0-20200324152954-d86554db4bab
go: extracting github.com/beltran/gssapi v0.0.0-20200324152954-d86554db4bab
xxdeMacBook-Pro:go xx$ go get -tags kerberos github.com/beltran/gosasl
go: finding github.com/beltran/gosasl latest
go: finding github.com/beltran/gssapi v0.0.0-20200324152954-d86554db4bab

* install gohive failed.
xxdeMacBook-Pro:go xx$ go get github.com/beltran/gohive
go: finding github.com/beltran/gohive v1.0.1
go: downloading github.com/beltran/gohive v1.0.1
go: extracting github.com/beltran/gohive v1.0.1
go: downloading github.com/beltran/gosasl v0.0.0-20181023043315-01c4c2ce6a51
go: extracting github.com/beltran/gosasl v0.0.0-20181023043315-01c4c2ce6a51
go: downloading github.com/beltran/gssapi v0.0.0-20180807003338-598f9f3b2878
go: extracting github.com/beltran/gssapi v0.0.0-20180807003338-598f9f3b2878
go: finding github.com/beltran/gosasl v0.0.0-20181023043315-01c4c2ce6a51
xxdeMacBook-Pro:go xx$ `go get -tags kerberos github.com/beltran/gohive`
go: finding github.com/beltran/gssapi v0.0.0-20180807003338-598f9f3b2878
#github.com/beltran/gssapi
pkg/mod/github.com/beltran/gssapi@v0.0.0-20180807003338-598f9f3b2878/name.go:26:39: error: typedef redefinition with different types ('const struct gss_name_struct *' vs 'const struct gss_name_t_desc_struct *')
typedef const struct gss_name_struct *gss_const_name_t;
                                      ^
/usr/local/opt/heimdal/include/gssapi/gssapi.h:94:46: note: previous definition is here
typedef const struct gss_name_t_desc_struct *gss_const_name_t;
                                             ^
1 error generated.

**Comment by beltran** [comment]
For some reason you're not picking the latest commit in gohive. I've created a release tag and you can install it with that with `go get github.com/beltran/gohive@v1.0.2`, you may get an error like `go: cannot use path@version syntax in GOPATH mode` in which case just run `export GO111MODULE=on` and retry.
This works for me in linux but I have a clean environment, it may help to just purge gohive as well before installing.

**Comment by damonlinn** [comment]
* now install kerberos  support have no issue , but run the program still encounter the same issue, any suggestion or wrong I did ? 

* make sure the environment is cleaned.

lfrdeMacBook-Pro:ckhive lfr$ sudo find / 2>/dev/null|egrep 'beltran|gohive'
lfrdeMacBook-Pro:ckhive lfr$ echo $GOPATH
/Users/lfr/go
lfrdeMacBook-Pro:ckhive lfr$ find $GOPATH 2>/dev/null|egrep 'beltran|gohive'
lfrdeMacBook-Pro:ckhive lfr$

* run command, still the same issue comes up.
lfrdeMacBook-Pro:ckhive lfr$ `go run main.go`
go: downloading github.com/beltran/gohive v1.0.2
go: extracting github.com/beltran/gohive v1.0.2
go: downloading github.com/beltran/gosasl v0.0.0-20200324154900-112336fc0fc0
go: extracting github.com/beltran/gosasl v0.0.0-20200324154900-112336fc0fc0
panic: gosasl was installed without kerberos support please reinstall with `go get` using the flags `build kerberos`

goroutine 1 [running]:
github.com/beltran/gosasl.NewGSSAPIMechanism(...)
        /Users/lfr/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200324154900-112336fc0fc0/no_gssapi.go:14
github.com/beltran/gohive.NewTSaslTransport(0x13a2840, 0xc0000a3020, 0x133ad22, 0x16, 0x13360d7, 0x6, 0xc0000f7c10, 0xc00001a456, 0x3, 0xc0000f03f0)
        /Users/lfr/go/pkg/mod/github.com/beltran/gohive@v1.0.2/sasl_transport.go:48 +0x524
github.com/beltran/gohive.Connect(0x133ad22, 0x16, 0x2710, 0x1336879, 0x8, 0xc0000fa000, 0xc0000f7f50, 0x100759f, 0xc0000260b8)
        /Users/lfr/go/pkg/mod/github.com/beltran/gohive@v1.0.2/hive.go:159 +0xe07
main.main()
        /Users/lfr/IdeaProjects/ckhive/main.go:13 +0xea
exit status 2

* install kerberos support , no issue.
lfrdeMacBook-Pro:ckhive lfr$ `go get -u -tags kerberos github.com/beltran/gohive`
go: downloading github.com/beltran/gssapi v0.0.0-20200324152954-d86554db4bab
go: extracting github.com/beltran/gssapi v0.0.0-20200324152954-d86554db4bab
go: finding github.com/beltran/gosasl latest
go: finding github.com/beltran/gssapi latest
lfrdeMacBook-Pro:ckhive lfr$ 
lfrdeMacBook-Pro:ckhive lfr$ `go get -u -tags kerberos github.com/beltran/gosasl`
go: finding github.com/beltran/gosasl latest
go: finding github.com/beltran/gssapi latest

lfrdeMacBook-Pro:ckhive lfr$ 

* run again, still same issue.
lfrdeMacBook-Pro:ckhive lfr$ `go run main.go`
panic: gosasl was installed without kerberos support please reinstall with `go get` using the flags `build kerberos`

goroutine 1 [running]:
github.com/beltran/gosasl.NewGSSAPIMechanism(...)
        /Users/lfr/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200324154900-112336fc0fc0/no_gssapi.go:14
github.com/beltran/gohive.NewTSaslTransport(0x13a2840, 0xc000099020, 0x133ad22, 0x16, 0x13360d7, 0x6, 0xc0000f9c10, 0xc0000ae3a6, 0x3, 0xc0000f23f0)
        /Users/lfr/go/pkg/mod/github.com/beltran/gohive@v1.0.2/sasl_transport.go:48 +0x524
github.com/beltran/gohive.Connect(0x133ad22, 0x16, 0x2710, 0x1336879, 0x8, 0xc0000fc000, 0xc0000f9f50, 0x100759f, 0xc00008c058)
        /Users/lfr/go/pkg/mod/github.com/beltran/gohive@v1.0.2/hive.go:159 +0xe07
main.main()
        /Users/lfr/IdeaProjects/ckhive/main.go:13 +0xea
exit status 2

lfrdeMacBook-Pro:ckhive lfr$  ll /Users/lfr/go/pkg/mod/github.com/beltran
total 0
dr-x------  16 lfr  staff  512  3 25 17:04 gohive@v1.0.2
dr-x------  13 lfr  staff  416  3 25 17:04 gosasl@v0.0.0-20200324154900-112336fc0fc0
dr-x------  27 lfr  staff  864  3 25 17:05 gssapi@v0.0.0-20200324152954-d86554db4bab

**Comment by beltran** [comment]
If that message is shown is because somewhere there's a regular installation of gosasl without kerberos support, I'm not sure why it's being picked up or where it may be, you could look inside `/Users/lfr/go`:
`cd /Users/lfr/go && find . -name gosasl` I'd expect more than one to show up. Just delete all of them and reinstall `gosasl`. I guess that the directory where it would be but it could be somewhere else.

**Comment by damonlinn** [comment]
Hi beltran,
     thanks for your time,I completely remove gosasl and reinstall again, but still not working,  I confirm that there is just one gosasl directory. and err message show that it call the method NewGSSAPIMechanism  in no_gssapi.go ,not gssapi.go.  the two files is in the same directory(
/Users/lfr/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200324154900-112336fc0fc0), is it normal？

lfrdeMacBook-Pro:beltran lfr$ `find $GOPATH -name gosasl`
/Users/lfr/go/pkg/mod/cache/download/github.com/beltran/gosasl
lfrdeMacBook-Pro:beltran lfr$ `find $GOPATH -type d|egrep 'gosasl.+'`
/Users/lfr/go/pkg/mod/cache/download/github.com/beltran/gosasl/@v
/Users/lfr/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200324154900-112336fc0fc0
lfrdeMacBook-Pro:beltran lfr$ ll /Users/lfr/go/pkg/mod/cache/download/github.com/beltran/gosasl/@v
total 72
-rw-r--r--  1 lfr  staff     33 Mar 26 09:46 v0.0.0-20181023043315-01c4c2ce6a51.mod
-rw-r--r--  1 lfr  staff      0 Mar 26 09:46 list.lock
-rw-r--r--  1 lfr  staff     78 Mar 26 09:46 v0.0.0-20181023043315-01c4c2ce6a51.info
-rw-r--r--  1 lfr  staff     70 Mar 26 09:46 list
-rw-r--r--  1 lfr  staff    112 Mar 26 09:46 v0.0.0-20200324154900-112336fc0fc0.mod
-rw-r--r--  1 lfr  staff     78 Mar 26 09:46 v0.0.0-20200324154900-112336fc0fc0.info
-rw-r--r--  1 lfr  staff      0 Mar 26 09:46 v0.0.0-20200324154900-112336fc0fc0.lock
-rw-------  1 lfr  staff  10762 Mar 26 09:46 v0.0.0-20200324154900-112336fc0fc0.zip
-rw-r--r--  1 lfr  staff     47 Mar 26 09:46 v0.0.0-20200324154900-112336fc0fc0.ziphash
lfrdeMacBook-Pro:beltran lfr$ ll /Users/lfr/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200324154900-112336fc0fc0
total 96
-r--r--r--  1 lfr  staff  1095 Mar 26 09:46 LICENSE
-r--r--r--  1 lfr  staff  1791 Mar 26 09:46 README.md
-r--r--r--  1 lfr  staff   112 Mar 26 09:46 go.mod
-r--r--r--  1 lfr  staff   450 Mar 26 09:46 go.sum
-r--r--r--  1 lfr  staff  8683 Mar 26 09:46 gssapi.go
-r--r--r--  1 lfr  staff   975 Mar 26 09:46 no_gssapi.go
-r--r--r--  1 lfr  staff  6203 Mar 26 09:46 sasl.go
-r--r--r--  1 lfr  staff   493 Mar 26 09:46 sasl_gssapi_test.go
-r--r--r--  1 lfr  staff  2087 Mar 26 09:46 sasl_test.go

lfrdeMacBook-Pro:beltran lfr$ `cd /Users/lfr/go/pkg/mod/github.com/beltran/gosasl@v0.0.0-20200324154900-112336fc0fc0; grep NewGSSAPIMechanism no_gssapi.go gssapi.go`
no_gssapi.go:// NewGSSAPIMechanism returns a new GSSAPIMechanism
no_gssapi.go:func NewGSSAPIMechanism(service string) (mechanism *GSSAPIMechanism, err error) {
gssapi.go:// NewGSSAPIMechanism returns a new GSSAPIMechanism
gssapi.go:func NewGSSAPIMechanism(service string) (mechanism *GSSAPIMechanism, err error) {
lfrdeMacBook-Pro:gosasl@v0.0.0-20200324154900-112336fc0fc0 lfr$

**Comment by beltran** [comment]
Sorry I think this has been my fault the whole time, you should be able to run it with `go run -tags kerberos main.go`, or if you build it with `go build -tags kerberos main.go && ./main`

**Comment by damonlinn** [comment]
Beltran, thank you for your patience, it works now.

**Comment by beltran** [comment]
Sure, happy it got solved.
